name = "protozoa"
version = "2.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
asset = ">= 1.2.0 and < 2.0.0"
birdie = ">= 1.4.0 and < 2.0.0"
pprint = ">= 1.0.6 and < 2.0.0"
glance = ">= 5.0.0 and < 6.0.0"
