//// Generated by Protozoa from app.proto, base.proto
//// 
//// This file is auto-generated and can be safely deleted and regenerated.
//// 
//// DO NOT EDIT THIS FILE MANUALLY - all changes will be lost on regeneration.

import gleam/int
import gleam/result
import gleam/string
import protozoa/decode
import protozoa/encode
import protozoa/wire

pub type BaseBaseStatus {
  UNKNOWN
  ACTIVE
  INACTIVE
}

pub type AppAppMessage {
  AppAppMessage(
    base: BaseBaseMessage,
    status: BaseBaseStatus,
  )
}

pub type BaseBaseMessage {
  BaseBaseMessage(
    id: String,
    status: BaseBaseStatus,
  )
}

pub fn encode_app_app_message(app_app_message: AppAppMessage) -> BitArray {
  encode.message([
    encode.field(1, wire.LengthDelimited, encode.length_delimited(encode_base_base_message(app_app_message.base))),
    encode.int32_field(2, encode_base_base_status_value(app_app_message.status)),
  ])
}

pub fn encode_base_base_message(base_base_message: BaseBaseMessage) -> BitArray {
  encode.message([
    encode.string_field(1, base_base_message.id),
    encode.int32_field(2, encode_base_base_status_value(base_base_message.status)),
  ])
}

pub fn app_app_message_decoder() -> decode.Decoder(AppAppMessage) {
  use base <- decode.then(decode.nested_message(1, base_base_message_decoder()))
  use status <- decode.then(decode_base_base_status_field(2))
  decode.success(AppAppMessage(base: base, status: status))
}

pub fn decode_app_app_message(data: BitArray) -> Result(AppAppMessage, List(decode.DecodeError)) {
  decode.run(data, app_app_message_decoder())
}

pub fn base_base_message_decoder() -> decode.Decoder(BaseBaseMessage) {
  use id <- decode.then(decode.string_with_default(1, ""))
  use status <- decode.then(decode_base_base_status_field(2))
  decode.success(BaseBaseMessage(id: id, status: status))
}

pub fn decode_base_base_message(data: BitArray) -> Result(BaseBaseMessage, List(decode.DecodeError)) {
  decode.run(data, base_base_message_decoder())
}

pub fn encode_base_base_status_value(value: BaseBaseStatus) -> Int {
  case value {
    UNKNOWN -> 0
    ACTIVE -> 1
    INACTIVE -> 2
  }
}

pub fn decode_base_base_status_field(field_num: Int) -> decode.Decoder(BaseBaseStatus) {
  decode.field(field_num, fn(field) {
    use value <- result.try(decode.int32_field(field))
    case value {
          0 -> Ok(UNKNOWN)
          1 -> Ok(ACTIVE)
          2 -> Ok(INACTIVE)
      _ -> Error(decode.DecodeError(expected: "valid base_base_status value", found: "Unknown base_base_status value: " <> string.inspect(value), path: []))
    }
  })
}

pub fn decode_base_base_status_value(value: Int) -> Result(BaseBaseStatus, String) {
  case value {
    0 -> Ok(UNKNOWN)
    1 -> Ok(ACTIVE)
    2 -> Ok(INACTIVE)
    _ -> Error("Unknown base_base_status value: " <> int.to_string(value))
  }
}

pub fn decode_repeated_base_base_status(field_num: Int) -> decode.Decoder(List(BaseBaseStatus)) {
  decode.repeated_field(field_num, fn(field) {
    use value <- result.try(decode.int32_field(field))
    decode_base_base_status_value(value)
    |> result.map_error(fn(err) { decode.DecodeError(expected: "base_base_status", found: err, path: []) })
  })
}