//// Generated by Protozoa from google/protobuf/empty.proto
//// 
//// This file is auto-generated and can be safely deleted and regenerated.
//// To regenerate all proto files, run: gleam run -m protozoa
//// 
//// DO NOT EDIT THIS FILE MANUALLY - all changes will be lost on regeneration.

import protozoa/decode
import protozoa/encode

pub type Empty {
  Empty
}

pub fn encode_empty(_empty: Empty) -> BitArray {
  encode.message([])
}

pub fn empty_decoder() -> decode.Decoder(Empty) {
  decode.success(Empty)
}

pub fn decode_empty(data: BitArray) -> Result(Empty, List(decode.DecodeError)) {
  decode.run(data, empty_decoder())
}
