//// Generated by Protozoa from google/protobuf/timestamp.proto
//// 
//// This file is auto-generated and can be safely deleted and regenerated.
//// To regenerate all proto files, run: gleam run -m protozoa
//// 
//// DO NOT EDIT THIS FILE MANUALLY - all changes will be lost on regeneration.

import protozoa/encode
import protozoa/decode





pub type Timestamp {
  Timestamp(
    seconds: Int,
    nanos: Int,
  )
}

pub fn encode_timestamp(timestamp: Timestamp) -> BitArray {
  encode.message([
    encode.int64_field(1, timestamp.seconds),
    encode.int32_field(2, timestamp.nanos),
  ])
}

pub fn timestamp_decoder() -> decode.Decoder(Timestamp) {
  use seconds <- decode.subrecord(decode.int64_with_default(1, 0))
  use nanos <- decode.subrecord(decode.int32_with_default(2, 0))
  decode.success(Timestamp(seconds: seconds, nanos: nanos))
}

pub fn decode_timestamp(data: BitArray) -> Result(Timestamp, decode.DecodeError) {
  decode.decode(data, timestamp_decoder())
}

